title: JustSkyDev
description: Docs Libs

remote_theme: CloudCannon/edition-jekyll-template@latest
plugins:
- jekyll-remote-theme

show_downloads: ["false"]

github: 
  repository_url: https://github.com/JustSkyDev/Bedrock-API
